### ISSUE TITLE
updating to ubuntu 20.04

### ISSUE THREAD

**Issue by 6lv1-blr** [MarvAmBass/docker-subversion#8]
thanks for your work, even if I think you don't use this container since a while.

I use a lot to learn docker this last week with your exemple and https://kb.synology.com/en-my/DSM/tutorial/How_to_launch_an_SVN_server_based_on_Docker_on_your_Synology_NAS

so it's working but little old (I read your FAQ about update and not using old container is a good advice)

I try an update and put it on github https://github.com/6lv1-blr/docker-ubuntu-svn-ssl-iF.SvnAdmin
but iF.SvnAdmin has a little issue but svnserver is working fine.

**Comment by MarvAmBass** [comment]
Hi there,

thanks for using my container. Unfortunately my FAQ is a bit outdated too ;) - I wrote it when docker was in an really early stage - a lot has changed since then.

I also don't recommend using svn - if you need a versioning and revision control system use `git`.

This container exists mainly for people who need to access or share legacy code etc.

I also don't recommend making this version available to the internet.

Maybe I will update this container to a newer version - but right now there is not much focus to it.


I just checked your repo, looks good - you also implemented my production settings which is important if you make it available to the internet.
Have fun using your container! But I won't update this repo out of fear breaking stuff at any of my users... there are many many many people using this container
